const gameLevels = [
    // --- NATURE & ELEMENTS ---
    { level: 1, emojis: ["☀️", "🌻"], answer: "SUNFLOWER", hint: "A yellow flower." },
    { level: 2, emojis: ["🌧️", "🏹"], answer: "RAINBOW", hint: "Colors in the sky." },
    { level: 3, emojis: ["❄️", "👨"], answer: "SNOWMAN", hint: "Man made of ice." },
    { level: 4, emojis: ["⭐", "🐟"], answer: "STARFISH", hint: "Star shaped fish." },
    { level: 5, emojis: ["🌙", "🚶"], answer: "MOONWALK", hint: "Dance move." },
    { level: 6, emojis: ["🌊", "🐴"], answer: "SEAHORSE", hint: "Sea creature." },
    { level: 7, emojis: ["🌍", "🐛"], answer: "EARTHWORM", hint: "Crawling insect." },
    { level: 8, emojis: ["🌲", "🍎"], answer: "PINEAPPLE", hint: "A thorny fruit." },
    { level: 9, emojis: ["⚡", "🐞"], answer: "THUNDERBOLT", hint: "Flash of light." },
    { level: 10, emojis: ["🔥", "🪰"], answer: "FIREFLY", hint: "Glow in the dark bug." },
    // --- FOOD & DRINKS ---
    { level: 11, emojis: ["🔥", "🐶"], answer: "HOTDOG", hint: "Sausage snack." },
    { level: 12, emojis: ["🧀", "🍔"], answer: "CHEESEBURGER", hint: "A meaty snack." },
    { level: 13, emojis: ["🥞", "🍰"], answer: "PANCAKE", hint: "Breakfast treat." },
    { level: 14, emojis: ["🍼", "🥛"], answer: "MILKSHAKE", hint: "Sweet cold drink." },
    { level: 15, emojis: ["🍿", "🌽"], answer: "POPCORN", hint: "Movie snack." },
    { level: 16, emojis: ["🥚", "🌱"], answer: "EGGPLANT", hint: "A vegetable." },
    { level: 17, emojis: ["🍯", "🌙"], answer: "HONEYMOON", hint: "Post-wedding trip." },
    { level: 18, emojis: ["🍇", "🍎"], answer: "FRUITCAKE", hint: "Sweet baked food." },
    { level: 19, emojis: ["🌶️", "🐶"], answer: "CHILLIDOG", hint: "Spicy snack." },
    { level: 20, emojis: ["🥤", "🧊"], answer: "ICEDRINK", hint: "Cold beverage." },
    // --- OBJECTS & TOOLS ---
    { level: 21, emojis: ["🔑", "🪵"], answer: "KEYBOARD", hint: "Typing tool." },
    { level: 22, emojis: ["👂", "💍"], answer: "EARRING", hint: "Ear jewelry." },
    { level: 23, emojis: ["🦷", "🖌️"], answer: "TOOTHBRUSH", hint: "Cleaning teeth." },
    { level: 24, emojis: ["🖐️", "💼"], answer: "HANDBAG", hint: "Carrying bag." },
    { level: 25, emojis: ["🚪", "🔔"], answer: "DOORBELL", hint: "Visitor signal." },
    { level: 26, emojis: ["💡", "🏠"], answer: "LIGHTHOUSE", hint: "Tower for ships." },
    { level: 27, emojis: ["🖊️", "🔪"], answer: "PENKNIFE", hint: "Small folder knife." },
    { level: 28, emojis: ["👟", "📦"], answer: "SHOEBOX", hint: "Box for footwear." },
    { level: 29, emojis: ["🧵", "🧺"], answer: "WASTEBASKET", hint: "Dustbin." },
    { level: 30, emojis: ["🔨", "🏠"], answer: "HAMMERHEAD", hint: "Type of shark." },
    // --- SPORTS & HOBBIES ---
    { level: 31, emojis: ["🦶", "⚽"], answer: "FOOTBALL", hint: "Popular sport." },
    { level: 32, emojis: ["🧺", "🏀"], answer: "BASKETBALL", hint: "Hoop game." },
    { level: 33, emojis: ["⚾", "🏏"], answer: "BASEBALL", hint: "Bat and ball game." },
    { level: 34, emojis: ["⛸️", " 📋 "], answer: "SKATEBOARD", hint: "Rolling board." },
    { level: 35, emojis: ["🏂", "❄️"], answer: "SNOWBOARD", hint: "Winter sport." },
    { level: 36, emojis: ["🌊", "🏄"], answer: "SURFBOARD", hint: "Riding waves." },
    { level: 37, emojis: ["🏃", "🏁"], answer: "RACEWAY", hint: "Track for racing." },
    // --- HOUSEHOLD & LIFE ---
    { level: 38, emojis: ["🏠", "💼"], answer: "HOUSEWORK", hint: "Daily chores." },
    { level: 39, emojis: ["🛏️", "⏰"], answer: "BEDTIME", hint: "Time to sleep." },
    { level: 40, emojis: ["☀️", "👓"], answer: "SUNGLASSES", hint: "Protect your eyes." },
    { level: 41, emojis: ["💄", "👄"], answer: "LIPSTICK", hint: "Makeup for lips." },
    { level: 42, emojis: ["🚿", "🧢"], answer: "SHOWERCAP", hint: "Bath headgear." },
    { level: 43, emojis: ["💇", "✂️"], answer: "HAIRCUT", hint: "New hairstyle." },
    { level: 44, emojis: ["🧼", "🧤"], answer: "DISHWASHER", hint: "Cleans plates." },
    { level: 45, emojis: ["📦", "📮"], answer: "MAILBOX", hint: "Receives letters." },
        // --- NATURE & WEATHER (CONTD.) ---
    { level: 46, emojis: ["❄️", "🌨️"], answer: "SNOWFALL", hint: "When snow falls from the sky." },
    { level: 47, emojis: ["☀️", "🔥"], answer: "SUNBURN", hint: "Skin damage from too much sun." },
    { level: 48, emojis: ["🌬️", "🪵"], answer: "WINDMILL", hint: "Structure that uses wind power." },
    { level: 49, emojis: ["🌧️", "💧"], answer: "RAINDROP", hint: "A single unit of rain." },
    { level: 50, emojis: ["🌊", "🐚"], answer: "SEASHELL", hint: "Found on the beach." },
    // --- ANIMALS & CREATURES ---
    { level: 51, emojis: ["🐶", "🏠"], answer: "DOGHOUSE", hint: "Small home for a pet." },
    { level: 52, emojis: ["🐷", "🏦"], answer: "PIGGYBANK", hint: "Where kids save coins." },
    { level: 53, emojis: ["🐝", "🪵"], answer: "BEEHIVE", hint: "Where bees live." },
    { level: 54, emojis: ["🦋", "🕸️"], answer: "BUTTERFLY", hint: "A colorful flying insect." },
    { level: 55, emojis: ["🐱", "🚶"], answer: "CATWALK", hint: "A narrow walkway or ramp." },
    { level: 56, emojis: ["🐞", "🐦"], answer: "LADYBUG", hint: "A small red beetle with spots." },
    { level: 57, emojis: ["🐂", "👦"], answer: "COWBOY", hint: "A man who herds cattle." },
    { level: 58, emojis: ["🐎", "👞"], answer: "HORSESHOE", hint: "Metal protection for a horse's foot." },
    { level: 59, emojis: ["🐑", "🪵"], answer: "SHEEPDOG", hint: "A dog trained to guard sheep." },
    { level: 60, emojis: ["🐉", "🪰"], answer: "DRAGONFLY", hint: "A fast-flying insect near water." },
    // --- DAILY OBJECTS ---
    { level: 61, emojis: ["🖐️", "⌚"], answer: "WRISTWATCH", hint: "Tells time on your arm." },
    { level: 62, emojis: ["📔", "🔖"], answer: "BOOKMARK", hint: "Helps you find your page." },
    { level: 63, emojis: ["🧴", "🥣"], answer: "SOAPBOWL", hint: "Holder for washing soap." },
    { level: 64, emojis: ["🕯️", "💡"], answer: "CANDLELIGHT", hint: "Light from a wax stick." },
    { level: 65, emojis: ["🛁", "🧼"], answer: "BATHTUB", hint: "Large container for washing." },
    { level: 66, emojis: ["🌂", "🧥"], answer: "RAINCOAT", hint: "Protective gear for wet weather." },
    { level: 67, emojis: [" टेबल", "🎾"], answer: "TABLETENNIS", hint: "Also known as Ping Pong." },
    { level: 68, emojis: ["🪜", "⚙️"], answer: "LADDERWORK", hint: "Climbing for repairs." },
    { level: 69, emojis: ["🔑", "🗝️"], answer: "KEYRING", hint: "Holds all your keys together." },
    { level: 70, emojis: ["👜", "📦"], answer: "HANDBAG", hint: "A small bag for personal items." },
    // --- FOOD & KITCHEN ---
    { level: 71, emojis: ["🍿", "🌽"], answer: "POPCORN", hint: "Snack made from corn." },
    { level: 72, emojis: ["🍯", "🐝"], answer: "HONEYCOMB", hint: "Structure made by bees." },
    { level: 73, emojis: ["🥛", "🍫"], answer: "MILKCHOCOLATE", hint: "Sweet brown candy." },
    { level: 74, emojis: ["🧊", "🍵"], answer: "ICETEA", hint: "Cold brewed beverage." },
    { level: 75, emojis: ["🥓", "🍳"], answer: "BREAKFAST", hint: "First meal of the day." },
    { level: 76, emojis: ["🍎", "🥧"], answer: "APPLEPIE", hint: "A classic baked fruit dessert." },
    { level: 77, emojis: ["🧀", "🍰"], answer: "CHEESECAKE", hint: "Rich creamy dessert." },
    { level: 78, emojis: ["🥜", "🧈"], answer: "PEANUTBUTTER", hint: "Creamy spread for bread." },
    { level: 79, emojis: ["🍇", "🍷"], answer: "GRAPEWINE", hint: "Drink made from grapes." },
    { level: 80, emojis: ["🍦", "🧁"], answer: "ICECUP", hint: "Small frozen treat." },
    // --- SPACE & SCIENCE ---
    { level: 81, emojis: ["🚀", "🚢"], answer: "SPACESHIP", hint: "Vehicle for outer space." },
    { level: 82, emojis: ["🔭", "⭐"], answer: "STARGAZE", hint: "Looking at the night sky." },
    { level: 83, emojis: ["🌎", "🗺️"], answer: "WORLDMAP", hint: "Drawing of the whole earth." },
    { level: 84, emojis: ["☀️", "🔦"], answer: "SUNLIGHT", hint: "Natural light from above." },
    { level: 85, emojis: ["🌙", "빔"], answer: "MOONBEAM", hint: "A ray of moonlight." },
    // --- WORK & LIFE ---
    { level: 86, emojis: ["💻", "👨"], answer: "COMPUTERMAN", hint: "Person working on PC." },
    { level: 87, emojis: ["📝", "📔"], answer: "NOTEBOOK", hint: "Where you write things down." },
    { level: 88, emojis: ["🪑", "👨"], answer: "CHAIRMAN", hint: "The leader of a meeting." },
    { level: 89, emojis: ["👮", "🐕"], answer: "POLICEDOG", hint: "K9 helper for the law." },
    { level: 90, emojis: ["🏥", "🛌"], answer: "SICKBED", hint: "Where you rest when ill." },
    { level: 91, emojis: ["🚶", "🛣️"], answer: "SIDEWALK", hint: "Path for people near the road." },
    { level: 92, emojis: ["🚩", "🚢"], answer: "FLAGSHIP", hint: "The most important ship." },
    { level: 93, emojis: ["🎨", "🖌️"], answer: "ARTWORK", hint: "Something created by an artist." },
    { level: 94, emojis: ["🎤", "📞"], answer: "MICROPHONE", hint: "Used to make voice louder." },
    { level: 95, emojis: ["🧠", " STORM"], answer: "BRAINSTORM", hint: "Thinking of new ideas." },
    // --- RANDOM FUN ---
    { level: 96, emojis: ["🃏", "📋"], answer: "CARDLIST", hint: "A list of playing cards." },
    { level: 97, emojis: ["🎈", "🎈"], answer: "BALLOONS", hint: "Filled with air at parties." },
    { level: 98, emojis: ["🎸", "🎸"], answer: "GUITARS", hint: "Musical instrument with strings." },
    { level: 99, emojis: ["🏰", "🏰"], answer: "CASTLES", hint: "Fortified stone homes." },
    { level: 100, emojis: ["🏆", "🏆"], answer: "TROPHIES", hint: "Awards for winning." },
    { level: 101, emojis: ["🏫", ["🚌"], "📚"], answer: "SCHOOLBUS", hint: "Vehicle that transports students to school." },
    { level: 102, emojis: ["🎥", "🍿", "🥤"], answer: "MOVIENIGHT", hint: "Watching films at home or theater with snacks." },
    { level: 103, emojis: ["🍔", " Fries ", "🥤"], answer: "FASTFOOD", hint: "Quick meals like burgers, fries, and soft drinks." },
    { level: 104, emojis: ["⛺", "🌲", "🔥"], answer: "CAMPFIRE", hint: "Outdoor fire used while camping in the woods." },
    { level: 105, emojis: ["🛒", "🥦", "🛍️"], answer: "GROCERY", hint: "Buying food and vegetables for home." },
    { level: 106, emojis: ["🏋️", "🏃", "🥗"], answer: "FITNESS", hint: "The lifestyle of exercising and eating healthy." },
    { level: 107, emojis: ["🎪", "🍿", "🤡"], answer: "CIRCUS", hint: "A classic show featuring clowns and acrobatics." },
    { level: 108, emojis: ["🎤", "🎸", "🥁"], answer: "ROCKBAND", hint: "A musical group with a singer, guitarist, and drummer." },
    { level: 109, emojis: ["🎈", "🍰", "🎁"], answer: "BIRTHDAY", hint: "Annual celebration with cake and gifts." },
    { level: 110, emojis: ["🎩", "🪄", "🃏"], answer: "MAGICIAN", hint: "A performer who does tricks using a wand and hat." },
    // --- SOUND & PHONETIC SYLLABLES (Perfect Sequence) ---
    { level: 111, emojis: ["👁️", "🍦", "🍦"], answer: "ICECREAM", hint: "Eye + Cream + Cream = Ice cream! A cold dessert." },
    { level: 112, emojis: ["☀️", "☀️", "☀️"], answer: "SUNNYDAYS", hint: "Sun + Sun + Sun = Bright, hot weather layout." },
    { level: 113, emojis: ["💧", "🍉", "🔫"], answer: "WATERMELON", hint: "Water + Melon concept. A large juicy summer fruit." },
    { level: 114, emojis: ["🌧️", "🧥", "💧"], answer: "RAINCOAT", hint: "Rain + Coat + Drop. Worn to stay dry." },
    { level: 115, emojis: ["🌊", "🏝️", "🛶"], answer: "ISLAND", hint: "Sea, isolated land, and a boat to reach there." },
    // --- TECH & DIGITAL LIFE ---
    { level: 116, emojis: ["💻", " Maus ", "💾"], answer: "SOFTWARE", hint: "Digital programs used inside a computer." },
    { level: 117, emojis: ["📱", "🎧", "🎵"], answer: "PLAYLIST", hint: "A collection of favorite songs on a smartphone." },
    { level: 118, emojis: ["🚗", "🛑", "🚦"], answer: "TRAFFIC", hint: "When cars stop due to signals on the road." },
    { level: 119, emojis: ["🔑", "🔒", "🔐"], answer: "PASSWORD", hint: "Secret security keys used to lock/unlock accounts." },
    { level: 120, emojis: ["🧠", "💡", "📝"], answer: "INVENTION", hint: "Using your brain to create a new original idea." },
    // --- NATURE & CLIMATE ---
    { level: 121, emojis: ["🏖️", "☀️", "🕶️"], answer: "SUMMER", hint: "Beach, sun, and sunglasses define this season." },
    { level: 122, emojis: ["❄️", "🧤", "🧣"], answer: "WINTER", hint: "Snow, gloves, and muffler used in cold days." },
    { level: 123, emojis: ["🌋", "🔥", "🪨"], answer: "VOLCANO", hint: "A mountain that shoots lava and hot rocks." },
    { level: 124, emojis: ["🌌", "🌙", "🔭"], answer: "STARGAZE", hint: "Looking through a telescope at night." },
    { level: 125, emojis: ["🏜️", "🐫", "☀️"], answer: "SAHARA", hint: "A very famous hot and sandy desert." },
    // --- ENVIRONMENT ---
    { level: 126, emojis: ["🌾", " ट्रैक्टर ", "👨‍🌾"], answer: "FARMLAND", hint: "Crops, tractor, and farmer working together." },
    { level: 127, emojis: ["🐠", "🐡", "🪸"], answer: "AQUARIUM", hint: "Where different colorful fishes live in water." },
    { level: 128, emojis: ["🌲", "🦊", "🪓"], answer: "FOREST", hint: "Trees, wild animals, and wood cutting." },
    { level: 129, emojis: ["✈️", "🧳", "🗺️"], answer: "TOURISM", hint: "Flying to places with luggage and maps." },
    { level: 130, emojis: ["🏹", "🎯", "🏆"], answer: "ARCHERY", hint: "Shooting arrows to hit the center target." },
    // --- TIMINGS & CHORES ---
    { level: 131, emojis: ["🎥", "🍿", "🎟️"], answer: "SHOWTIME", hint: "Movie, popcorn, and tickets mean the show is on." },
    { level: 132, emojis: ["🍳", "🍞", "🥛"], answer: "BREAKFAST", hint: "Eggs, bread, and milk form the first meal." },
    { level: 133, emojis: ["⏰", "🥱", "🛏️"], answer: "WAKINGUP", hint: "Alarm ringing, yawning, and leaving bed." },
    { level: 134, emojis: ["🧼", "🧺", "👕"], answer: "LAUNDRY", hint: "Soap, basket, and clothes to be washed." },
    { level: 135, emojis: ["📰", " Glasses ", "☕"], answer: "NEWSLETTER", hint: "Reading updates with morning coffee." },
    { level: 136, emojis: ["🦁", "🐯", "🦓"], answer: "WILDLIFE", hint: "Lions, tigers, and zebras in nature." },
    { level: 137, emojis: ["🐶", "🦴", "🐕"], answer: "DOGLOVER", hint: "Someone who treats puppies with bones and care." },
    { level: 138, emojis: ["🕷️", "🕸️", "🏚️"], answer: "HAUNTED", hint: "Spiders, webs, and broken empty houses." },
    { level: 139, emojis: ["🎄", "🎅", "🎁"], answer: "XMASGIFT", hint: "Christmas tree and Santa bringing presents." },
    { level: 140, emojis: ["🎃", "🍬", "👻"], answer: "HALLOWEEN", hint: "Pumpkin sweets and spooky ghost themes." },
    // --- FESTIVALS & SPECIALS ---
    { level: 141, emojis: ["🌟", "🎆", "🥂"], answer: "NEWYEAR", hint: "Celebrating midnight fireworks and stars." },
    { level: 142, emojis: ["👔", "💼", "🏢"], answer: "OFFICE", hint: "Tie, briefcase, and corporate building." },
    { level: 143, emojis: ["🚀", "🛰️", "👽"], answer: "UNIVERSE", hint: "Rocket, satellite, and aliens in deep space." },
    { level: 144, emojis: ["🍫", "🍬", "🍩"], answer: "SWEETS", hint: "Chocolates, candies, and donuts." },
    { level: 145, emojis: ["👑", "🏰", "🛡️"], answer: "KINGDOM", hint: "Crown, castle, and protective shield." },
    { level: 146, emojis: ["⚡", "🔌", "🔋"], answer: "CHARGER", hint: "Power, plug, and battery status." },
    { level: 147, emojis: ["🔥", "🍳", "👨‍🍳"], answer: "COOKING", hint: "Fire, pan, and a professional chef." },
    { level: 148, emojis: ["🏁", "🏎️", "🏆"], answer: "RACING", hint: "Checkered flag, sports car, and trophy." },
    { level: 149, emojis: ["🩺", "💊", "🏥"], answer: "MEDICAL", hint: "Stethoscope, pills, and clinical care." },
    { level: 150, emojis: ["🎵", "🎤", "🕺"], answer: "POPDANCE", hint: "Music notes, singing, and dancing on stage." },
    { level: 151, emojis: ["⏰", "🪱", "🐦", "🐛"], answer: "EARLYBIRD", hint: "A phrase for someone who wakes up very early (The early bird catches the worm)." },
    { level: 152, emojis: ["🍎", "📅", "🩺", "🙅"], answer: "HEALTHY", hint: "Based on the proverb: An apple a day keeps the doctor away." },
    { level: 153, emojis: ["🐈", "🌧️", "🐕", "🌧️"], answer: "RAINCATSANDDOGS", hint: "An English idiom that means it is raining very heavily." },
    { level: 154, emojis: ["🤫", "🔇", "🥇", "🏆"], answer: "SILENCEISGOLDEN", hint: "A famous saying that means speaking less is often best." },
    { level: 155, emojis: ["❌", "🐝", "🗺️", "🏠"], answer: "NOWHERE", hint: "No + Bee + Where (Map) + Home. Means not in any place." },
    // --- TIME & SEASONS PHRASES ---
    { level: 156, emojis: ["❄️", "☃️", "🎿", "🏂"], answer: "WINTERSPORTS", hint: "Activities and games played only on snow and ice." },
    { level: 157, emojis: ["☀️", "🏖️", "🏐", "🍉"], answer: "SUMMERFUN", hint: "Beach activities, games, and fruits enjoyed during hot holidays." },
    { level: 158, emojis: ["⏰", "✈️", "🗺️", "🧳"], answer: "TIMETOTRAVEL", hint: "The perfect moment to pack bags and go on a vacation." },
    { level: 159, emojis: ["🌙", "🦉", "🌟", "💤"], answer: "NIGHTOWL", hint: "A person who stays awake and active very late at night." },
    { level: 160, emojis: ["🌅", "🍳", "☕", "📰"], answer: "MORNINGROUTINE", hint: "Sunrise, breakfast, coffee, and news done every day start." },
    // --- ADVANCED COMPOUND WORDS ---
    { level: 161, emojis: ["🔥", "🛡️", "👨‍🚒", "🚒"], answer: "FIREFIGHTER", hint: "A brave person trained to put out dangerous fires." },
    { level: 162, emojis: ["🍔", "🍟", "🍕", "🥤"], answer: "JUNKFOOD", hint: "Unhealthy restaurant foods packed with calories." },
    { level: 163, emojis: ["🎥", "🍿", "🎟️", "🎬"], answer: "MOVIEDIRECTOR", hint: "The person who controls the making of a film." },
    { level: 164, emojis: ["🚀", "👨‍🚀", "🌌", "🛰️"], answer: "ASTRONAUT", hint: "A space traveler who explores planets and stars." },
    { level: 165, emojis: ["💻", "👨‍💻", "⚙️", "🌐"], answer: "WEBDEVELOPER", hint: "A professional who codes and builds websites." },
    // --- SPORTS & MEGA EVENTS ---
    { level: 166, emojis: ["🏆", "🥇", "🥈", "🥉"], answer: "MEDALIST", hint: "A champion who wins gold, silver, or bronze." },
    { level: 167, emojis: ["🏃", "🏁", "👟", "⏱️"], answer: "MARATHON", hint: "A very long-distance running race check by time." },
    { level: 168, emojis: ["🌲", "🏕️", "🎒", "🥾"], answer: "CAMPINGTRIP", hint: "Going into the forest for hiking and sleeping in tents." },
    { level: 169, emojis: ["♣️", "♦️", "♥️", "♠️"], answer: "CARDGAME", hint: "A game played using a full deck of playing cards." },
    { level: 170, emojis: ["🏁", "🏎️", "🔧", "⛽"], answer: "RACETRACK", hint: "Where high-speed cars race and take pit stops." },
    // --- LIFE & STORIES ---
    { level: 171, emojis: ["👑", "🏰", "💂", "🛡️"], answer: "ROYALPALACE", hint: "The heavily guarded official home of a king." },
    { level: 172, emojis: ["🏴‍☠️", "🦜", "🪙", "🗺️"], answer: "TREASURE", hint: "Pirate, parrot, and gold coins hidden on a map." },
    { level: 173, emojis: ["🎃", "👻", "🦇", "🧛"], answer: "SPOOKYNIGHT", hint: "Halloween elements like ghosts, bats, and vampires." },
    { level: 174, emojis: ["🧪", "🧬", "🔬", "🥼"], answer: "SCIENTIST", hint: "A person who does experiments in a professional lab." },
    { level: 175, emojis: ["🎈", "🎂", "🥳", "🎁"], answer: "PARTYTIME", hint: "Balloons, cake, and joy mean a celebration is happening." },
    // --- REBUS PHONETICS (Strict Sequence Match) ---
    { level: 176, emojis: ["🖐️", "🪙", "🙅", "🪰"], answer: "HANDMADE", hint: "Hand + Coin (Money) + No + Fly. Means crafted by hand." },
    { level: 177, emojis: ["🚗", "🐕", "🛒", "📦"], answer: "CARGO", hint: "Car + Dog (Go!) + Cart + Box. Means goods carried by ship/plane." },
    { level: 178, emojis: ["🐮", "👦", "🤠", "👢"], answer: "COWBOYLIFE", hint: "Cow + Boy + Hat + Boots. Defines the wild west lifestyle." },
    { level: 179, emojis: ["🖊️", "🍏", "🍍", "🖊️"], answer: "PPAP", hint: "Based on the viral song: Pen-Pineapple-Apple-Pen!" },
    { level: 180, emojis: ["💧", "🍉", "🧊", "🥤"], answer: "MELONJUICE", hint: "Water + Melon + Ice + Straw. A refreshing summer drink." },
    // --- DAILY LOGIC ---
    { level: 181, emojis: ["👔", "💼", "👞", "🏢"], answer: "WORKPLACE", hint: "Formal clothes and briefcase used to go to office." },
    { level: 182, emojis: ["🛒", "🏬", "💳", "🛍️"], answer: "SHOPPING", hint: "Going to a mall, swiping a card, and buying bags." },
    { level: 183, emojis: ["📱", "📶", "💬", "❤️"], answer: "CHATTING", hint: "Using phone signals to send text messages and likes." },
    { level: 184, emojis: ["🧼", "🧽", "🧹", "✨"], answer: "CLEANING", hint: "Using soap, sponge, and broom to make a room shine." },
    { level: 185, emojis: ["🏫", "🎒", "📝", "💯"], answer: "EXAMINATION", hint: "Studying hard at school to score top marks." },
    // --- ANIMAL HABITATS ---
    { level: 186, emojis: ["🦁", "🦒", "🐘", "🐒"], answer: "ZOOLAND", hint: "A place where wild animals are kept for people to see." },
    { level: 187, emojis: ["🐠", "🐙", "🦈", "🌊"], answer: "OCEANLIFE", hint: "Fishes, octopuses, and sharks living deep in the sea." },
    { level: 188, emojis: ["🐕", "🐈", "🦜", "🐇"], answer: "PETANIMALS", hint: "Friendly animals that people keep inside their homes." },
    { level: 189, emojis: ["🐓", "🐖", "🐄", "🚜"], answer: "FARMANIMALS", hint: "Roosters, pigs, and cows living near a tractor barn." },
    { level: 190, emojis: ["🪱", "🐛", "🐜", "🕷️"], answer: "INSECTS", hint: "Small crawling bugs and creatures found in nature." },
    // --- EXTRA MIND SHARPENERS ---
    { level: 191, emojis: ["🎵", "🎹", "🎻", "🎺"], answer: "ORCHESTRA", hint: "A large group of musicians playing classical instruments." },
    { level: 192, emojis: ["⚡", "🔌", "🔋", "🔋"], answer: "POWERBANK", hint: "An external device used to charge empty phone batteries." },
    { level: 193, emojis: ["🧠", "⚡", "🧩", "🏆"], answer: "BRAINTEASER", hint: "A difficult puzzle meant to test your intelligence." },
    { level: 194, emojis: ["👑", "💎", "💍", "🪙"], answer: "TREASURE", hint: "Valuable items like crowns, diamonds, and old coins." },
    { level: 195, emojis: ["🍕", "🍔", "🍦", "🍩"], answer: "CHEATMEAL", hint: "Eating your favorite fast food after a long diet." },
    { level: 196, emojis: ["🏥", "🩺", "💊", "🚑"], answer: "HEALTHCARE", hint: "The system of medical treatment, clinics, and medicines." },
    { level: 197, emojis: ["🛫", "☁️", "🛬", "🌍"], answer: "FLIGHT", hint: "Taking off into the clouds and landing in another country." },
    { level: 198, emojis: ["🖊️", "📝", "📖", "🎓"], answer: "EDUCATION", hint: "Writing, reading books, and graduating with a degree." },
    { level: 199, emojis: ["💵", "💰", "💳", "🏦"], answer: "BANKING", hint: "Managing your cash, wealth, and cards at a financial place." },
    { level: 200, emojis: ["⭐", "🌟", "✨", "🎉"], answer: "SUCCESSZONE", hint: "Our ultimate target! Celebrations, bright stars, and victory!" },
    { 
      level: 201, 
      emojis: ["⭐", "💵"], 
      answer: "STARBUCKS", 
      hint: "A very famous international coffee brand (Star + Bucks)." },
    { 
        level: 202, 
        emojis: ["🐱", "🐟"], 
        answer: "CATFISH", 
        hint: "A type of fish with whiskers, or a slang for a fake online profile." 
    },
    { 
      level: 203, 
      emojis: ["⏰", "🪙"], 
      answer: "QUARTER", 
      hint: "A fraction (1/4), 15 minutes on a clock, or a 25-cent coin in America." },
     { 
      level: 204, 
      emojis: ["🧠", "🌊"], 
      answer: "BRAINSTORM", 
      hint: "Brain + Storm. A sudden bright idea or a group discussion to solve a problem." },
      { 
        level: 205, 
        emojis: ["👂", "🐚"], 
        answer: "EARSHELL", 
        hint: "Ear + Shell. The external anatomy of the human ear (Pinna)." },
      { 
        level: 206, 
        emojis: ["💵", "🪟"], 
        answer: "BILLBOARD", 
        hint: "Bill (Money) + Board (Window/Frame). A large outdoor advertising structure." },
      { 
        level: 207, 
        emojis: ["🌱", "🗄️"], 
        answer: "BACKGROUND", 
        hint: "Back (Seed/Sprout from behind) + Ground (Cabinet base). The area behind the main object." },
      { 
        level: 208, 
        emojis: ["🔥", "🏢"], 
        answer: "CAMPUS", 
        hint: "Camp (Fire) + Us (Building/Community). The grounds and buildings of a university." },
      { 
        level: 209, 
        emojis: ["👑", "🌐"], 
        answer: "CROWNWEB", 
        hint: "Crown + Web (Internet/Network). The top structural network or a digital crowning architecture." },
      { 
        level: 210, 
        emojis: ["🍞", "🏆"], 
        answer: "BREADWINNER", 
        hint: "Bread (Food) + Winner (Trophy). The primary financial earner of a family." 
    }
];
